version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Порт для подключения к RabbitMQ
      - "15672:15672"  # Порт для Web UI
    environment:
      - RABBITMQ_DEFAULT_USER=user  # Имя пользователя
      - RABBITMQ_DEFAULT_PASS=password  # Пароль
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
